### PR TITLE
New branch for Code Review

### PR DESCRIPTION
**Pull request by ijklmopffs**

### CODE REVIEW

**Comment by kinsomicrote** [comment]
There is nothing on the branch for me to review.

**Comment by ijklmopffs** [comment]
Main file for review is the Plan.jsx. Want to know if there's a better way of rendering the pricing on the modal tab.

**Comment by kinsomicrote** [comment]
The purpose of creating the PR is that the file be attached to the PR for it to be reviewed. There's no way to review it if it's not on the PR.
You might have to remove the file(s) from the main branch first. Then create a new PR with the file(s) attached. Or use this PR.
Point is, when I click on the changes tab of the PR, the files to the reviewed should be there.

**Comment by ijklmopffs** [comment]
Alright. File to be reviewed has been added to the PR

**Comment by kinsomicrote** [comment]
Just to be clear, this is the content of the PR:
image


There is nothing to comment on here. Everything looks great to me. I noticed more contents in the file that are not captured in the PR. If you need those reviewed, you'll need to do what I suggested - remove the file(s) from the main branch. Create a new PR with the files attached.

**Pull request closed without merging**
